apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
  labels:
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
      - name: nginx
        image: nginx:latest
     
 
