---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-secret
  labels:
    type: sec-test
spec:
  replicas: 1
  selector:
    matchLabels:
      type: sec-test
  template:
    metadata:
      name: sec-pod
      labels:
        type: sec-test
    spec:
      containers:
      - image: mysql:8
        name: sec-con
        envFrom:
        - secretRef:
            name: test-secret
        
    


