apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
     
 
