apiVersion: apps/v1
kind: Deployment
metadata:
  name: hog      
  labels:
    app: hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hog
  template:
    metadata:
      labels:
        app: hog
    spec:
      containers:
      - image: vish/stress
        name: stress
        resources:
          limits:
            memory: "4Gi"
          requests:
             memory: "2500Mi"
        args:
        - -cpus
        - "2"
        - -mem-total
        - "550Mi"
        - -mem-alloc-size
        - "500Mi"
        - -mem-alloc-sleep
        - "1s"

