---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns

---

kind: ResourceQuota
apiVersion: v1
metadata:
  name: test-rq
  namespace: test-ns
spec:
  hard:
   pods: "1"

--

kind: Pod
apiVersion: v1
metadata:
  name: my-pod
  namespace: test-ns
spec:
  containers:
  - image: nginx
    name: test-con
   
