apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "k8"
            operator: In
            values:
            - "playarea"
   
