apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod
  labels:
    type: web
spec:
  containers:
   - name: my-nginx
     image: nginx
     env:
       - name: PORT_ENV
         valueFrom:
           configMapKeyRef:
             name: appl-config
             key: APP_DATA_PORT
  

