apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-05T15:45:23Z"
  labels:
    run: simple-pod
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:containers:
          k:{"name":"simple-pod"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl-run
    operation: Update
    time: "2021-01-05T15:45:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.1.0.138"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-01-05T15:45:33Z"
  name: simple-pod
  namespace: default
  resourceVersion: "946135"
  selfLink: /api/v1/namespaces/default/pods/simple-pod
  uid: 66c22fe6-66b2-4f22-870a-589b1890f2d7
spec:
  containers:
  - image: kubernetes/pause
    imagePullPolicy: Always
    name: simple-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-brt5b
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-brt5b
    secret:
      defaultMode: 420
      secretName: default-token-brt5b
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-05T15:45:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-05T15:45:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-05T15:45:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-05T15:45:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7882b7989f4414393793a0c993c7fab7ae33f53988bbfd0e4c0b5cdb965b34d6
    image: kubernetes/pause:latest
    imageID: docker-pullable://kubernetes/pause@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105
    lastState: {}
    name: simple-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-05T15:45:32Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.138
  podIPs:
  - ip: 10.1.0.138
  qosClass: BestEffort
  startTime: "2021-01-05T15:45:23Z"
