apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
  labels:
    type: web
spec:
  template:
    metadata:
      name: my-web-pod
      labels:
        type: web-pod
    spec:
      containers:
        - name: my-container
          image: nginx
  replicas: 3      
      
 
