apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-po
  name: test-po
spec:
  containers:
  - image: busybox:1.28
    name: test-po
    resources: {}
    command:
    - sleep
    - "4800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
