kind: Pod
apiVersion: v1
metadata:
   name: pintoford
   namespace: default
spec:
 containers:
 - image: alpine 
   name: gastank
   command:
   - sleep
   - "3600"
   volumeMounts:
   - mountPath: /scratch
     name: scratch-volume
 volumes:
 - name: scratch-volume
   hostPath:
      path: /home/ubuntu
      type: Directory      
