apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      containers:
      - image: fluent/fluentd:stable
        name: fluentd
        resources:
          limits:
            memory: 200Mi
        volumeMounts:
        - name: fluentd-conf
          mountPath: /fluentd/etc
        env:
        - name: FLUENTD_CONF
          value: "fluentd-kube.conf"
      volumes:
      - name: fluentd-conf
        configMap:
          name: fluentd-config
      terminationGracePeriodSeconds: 30 
